### PR TITLE
0.7

### PR DESCRIPTION
**Pull request by ekryski**
This PR does a whole bunch of stuff:

- Adds an example to generated plugin
- Updates plugin generator readme
- Updates generated readme
- Fixes deprecated yeoman test utils call
- Removes `yo` as a peer dependency
- Makes mocha tests recursive
- Updates dependencies
- Converts tests over to Chai's `expect` syntax
- Makes starting index file more realistic
- removes lodash dependency

### CODE REVIEW

**Comment by daffl** [comment]
Is there anything wrong with the built-in `assert`?

**Comment by ekryski** [comment]
@daffl no not really it's just that I want things to be consistent. We are now using chai in a bunch of the modules because of it's nice support for asserting on sinon spies, stubs, etc. I plan on slowly migrating the other repos over.

Chai it pretty lightweight so it's not much overhead and I personally prefer the `expect` syntax as I find it easier to read.

**Comment by daffl** [comment]
Done. v0.7.0 is 🚢ed

**Comment by ekryski** [comment]
Woot!

**Pull request merged**
